### ISSUE TITLE
Parameters order in "Controllers\Base::renderHtml" method

### ISSUE THREAD

**Issue by hakobyansen** [Neuron-PHP/mvc#1]
https://github.com/Neuron-PHP/mvc/blob/843cfa3d2493c993475897a0540fc9df82bd22bf/src/Mvc/Controllers/Base.php#L22

I often don't need to pass any data from controller to the view, e.g. in case of simple "create" forms, landing pages etc., but I always have to pass empty array as data, because I almost always have to specify a page name to the 2nd parameter. For example:

```php
return $this->renderHtml([], "create");
```

I suggest to change the order of the parameters - make the `$Page` to be 1st parameter, and `$Data` - 2nd so I will need just specify the view name only:

```php
return $this->renderHtml("create");
```

**Comment by ljonesfl** [comment]
@c0d3b0t is this still an issue with PHP8, based on named arguments?

**Comment by hakobyansen** [comment]
No @ljonesfl 😃
